export const SET_MAXIMIZED = "SET_MAXIMIZED";
export const GET_VIDEO_INFO = "GET_VIDEO_INFO";
export const SET_RESULTS_LOADING = "SET_RESULTS_LOADING";
export const GET_SINGLE_VIDEO_INFO = "GET_SINGLE_VIDEO_INFO";
export const GET_SINGLE_VIDEO_INFO_ERR = "GET_SINGLE_VIDEO_INFO_ERR";

export const ADD_TO_JOB_LIST = "ADD_TO_JOB_LIST";
export const REMOVE_FROM_JOB_LIST = "REMOVE_TO_JOB_LIST";
export const SET_JOB_FORMAT = "SET_JOB_FORMAT";
export const SET_GENERAL_JOB_FORMAT = "SET_GENERAL_JOB_FORMAT";
export const RESET_ALL_JOBS_FORMAT = "RESET_ALL_JOBS_FORMAT";
export const CLEAR_JOBS = "CLEAR_JOBS";
export const SET_SAVE_DIRECTORY = "SET_SAVE_DIRECTORY";

export const SET_PROGRESS_STATUS = "SET_PROGRESS_STATUS";
export const SET_TOTAL_PROGRESS = "SET_TOTAL_PROGRESS";
export const SHOW_STATUS_BAR = "SHOW_STATUS_BAR";
export const SHOW_PROGRESS_BAR = "SHOW_PROGRESS_BAR";
