export const SET_MAXIMIZED = "SET_MAXIMIZED";
export const GET_VIDEO_INFO = "GET_VIDEO_INFO";
export const SET_RESULTS_LOADING = "SET_RESULTS_LOADING";
export const GET_SINGLE_VIDEO_INFO = "GET_SINGLE_VIDEO_INFO";
export const GET_SINGLE_VIDEO_INFO_ERR = "GET_INFO_ERR";
export const GET_PLAYLIST_INFO = "GET_PLAYLIST_INFO";
export const GET_PLAYLIST_INFO_ERR = "GET_INFO_ERR";
export const SET_RESULT_FORMAT = "SET_RESULT_FORMAT";
export const CLEAR_RESULTS = "CLEAR_RESULTS";

export const SET_EMBEDDED_PLAYLIST_DETAILS = "SET_EMBEDDED_PLAYLIST_DETAILS";
export const CLEAR_EMBEDDED_PLAYLIST_DETAILS =
    "CLEAR_EMBEDDED_PLAYLIST_DETAILS";

export const ADD_TO_JOB_LIST = "ADD_TO_JOB_LIST";
export const ADD_MULTIPLE_TO_JOB_LIST = "ADD_MULTIPLE_TO_JOB_LIST";
export const REMOVE_FROM_JOB_LIST = "REMOVE_TO_JOB_LIST";
export const SET_JOB_FORMAT = "SET_JOB_FORMAT";
export const SET_GENERAL_JOB_FORMAT = "SET_GENERAL_JOB_FORMAT";
export const RESET_ALL_JOBS_FORMAT = "RESET_ALL_JOBS_FORMAT";
export const CLEAR_JOBS = "CLEAR_JOBS";
export const CLEAR_COMPLETE_JOBS = "CLEAR_COMPLETE_JOBS";
export const SET_SAVE_DIRECTORY = "SET_SAVE_DIRECTORY";

export const ADD_JOB_WITH_LOOKUP_ERROR = "ADD_JOB_WITH_LOOKUP_ERROR";

export const DOWNLOAD_START = "DOWNLOAD_START";
export const DOWNLOAD_COMPLETE = "DOWNLOAD_COMPLETE";
export const DOWNLOAD_PROGRESS = "DOWNLOAD_PROGRESS";
export const DOWNLOAD_BULK_PROGRESS = "DOWNLOAD_BULK_PROGRESS";
export const DOWNLOAD_ERROR = "DOWNLOAD_ERROR";

export const SET_PROGRESS_STATUS = "SET_PROGRESS_STATUS";
export const SET_TOTAL_PROGRESS = "SET_TOTAL_PROGRESS";
export const SHOW_STATUS_BAR = "SHOW_STATUS_BAR";
export const SHOW_PROGRESS_BAR = "SHOW_PROGRESS_BAR";
